<?php

namespace TerAelis\TChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getLast($idSalon, $date, $max = -1) {
        $query = $this->createQueryBuilder('m')
                ->join('m.user', 'u')
                ->addSelect('u')
                ->join('m.salon', 's')
                ->where('s.id = :idSalon')
                ->andWhere('m.createdAt >= :date')
                ->setParameter('idSalon', $idSalon)
                ->setParameter('date', $date);
        if($max > 0) {
            $query = $query->setMaxResults($max);
        }
        return $query->orderBy('m.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getNumberById($id) {
        return $this->createQueryBuilder('m')
            ->select('COUNT(m.id)')
            ->join('m.user', 'a')
            ->where('a.id = '.$id)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getMessage($id) {
        return $this->createQueryBuilder('m')
            ->join('m.salon', 's')
            ->addSelect('s')
            ->where('m.id = '.$id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
