<?php

namespace TerAelis\StatistiquesBundle\Entity;

/**
 * DailyUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyUpdateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastUpdate()
    {
        return $this->createQueryBuilder('lu')
            ->orderBy('lu.lastUpdate', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
