<?php

namespace TerAelis\StatistiquesBundle\Entity;

/**
 * MembreStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreStatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBestUser($nb)
    {
        return $this->createQueryBuilder('s')
            ->join('s.membre', 'u')
            ->addSelect('u')
            ->addSelect('sum(s.nbCommentaire) as nb_commentaire')
            ->addSelect('sum(s.nbSujet) as nb_sujet')
            ->addSelect('sum(s.nbSujet) + sum(s.nbCommentaire) as hidden nb_total')
            ->groupBy('u.id')
            ->orderBy('nb_total', 'DESC')
            ->setMaxResults($nb)
            ->getQuery()
            ->getResult();
    }

    public function findBestUserMonthly($nb)
    {
        $date = (new \DateTime())->modify('-1 months');
        return $this->createQueryBuilder('s')
            ->join('s.membre', 'u')
            ->addSelect('u')
            ->addSelect('sum(s.nbCommentaire) as nb_commentaire')
            ->addSelect('sum(s.nbSujet) as nb_sujet')
            ->addSelect('sum(s.nbSujet) + sum(s.nbCommentaire) as hidden nb_total')
            ->groupBy('u.id')
            ->orderBy('nb_total', 'DESC')
            ->where('s.date > :start')
            ->setParameter(':start', $date)
            ->setMaxResults($nb)
            ->getQuery()
            ->getResult();
    }
}
