<?php

namespace TerAelis\StatistiquesBundle\Entity;

/**
 * PoleStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoleStatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPeriod($byPeriod, $dateStart, $dateEnd)
    {
        switch ($byPeriod) {
            case 'month':
                return $this->createQueryBuilder('s')
                    ->select('s.pole')
                    ->addSelect('sum(s.nbSujet) as nb_sujet')
                    ->addSelect('sum(s.nbCommentaire) as nb_commentaire')
                    ->addSelect('SUBSTRING(s.date, 6, 2) as month')
                    ->addSelect('min(s.date) as date')
                    ->groupBy('s.pole')
                    ->addGroupBy('month')
                    ->orderBy('date', 'DESC')
                    ->where('s.date > :dateStart')
                    ->andWhere('s.date <= :dateEnd')
                    ->setParameter(':dateStart', $dateStart)
                    ->setParameter(':dateEnd', $dateEnd)
                    ->getQuery()
                    ->getArrayResult();
                break;
        }
    }
}
