<?php

namespace TerAelis\StatistiquesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsRepository extends EntityRepository
{
    public function getLastStats() {
        $stats = $this->createQueryBuilder('s')
            ->orderBy('s.id', 'DESC')
            ->getQuery()
            ->setMaxResults(1)
            ->getResult();
        $res = null;
        foreach ($stats as $s) {
            $res = $s;
        }
        return $res;
    }

    public function needUpdate() {
        $res = true;
        $stats = $this->getLastStats();
        if($stats != null) {
            $now = new \DateTime();
            $then = $stats->getLastUpdate(); // "2012-07-18 21:11:12" for example
            $diff = $now->diff($then);
            $minutes = ($diff->format('%a') * 1440) + // total days converted to minutes
                ($diff->format('%h') * 60) +   // hours converted to minutes
                $diff->format('%i');          // minutes
            $res = $minutes > 30;
        }

        return $res;
    }
}
