<?php

namespace TerAelis\StatistiquesBundle\Entity;

/**
 * SujetStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetStatRepository extends \Doctrine\ORM\EntityRepository
{
}
