<?php

namespace TerAelis\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaliseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaliseRepository extends EntityRepository
{
    public function getCategorie($idCategorie) {

        return $this->createQueryBuilder('b')
            ->join('b.categorie', 'c')
            ->where('c.id = :id')
            ->setParameter('id', $idCategorie);
    }
}
