<?php

namespace TerAelis\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoixRepository extends EntityRepository
{
    public function getChoix($idSujet) {
        return $this
            ->createQueryBuilder('c')
            ->join('c.sondage', 's')
            ->join('s.post', 'p')
            ->where('p.id = '.$idSujet)
            ->getQuery()
            ->getResult();
    }
}