<?php

namespace TerAelis\ForumBundle\Entity;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNext($nb = 5)
    {
        $builder = $this->createQueryBuilder('e')
            ->where('e.date > :today')
            ->setParameter(':today', new \DateTime())
            ->orderBy('e.priority', 'DESC')
            ->addOrderBy('e.date');
        if(!empty($nb)) {
            $builder = $builder->setMaxResults($nb);
        }
        return $builder->setMaxResults($nb)
            ->getQuery()
            ->getResult();
    }
}
