<?php

namespace TerAelis\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findByNames($arrayTag) {
        $where = "";
        foreach($arrayTag as $t) {
            $where = $where." or t.tag = '".$t."'";
        }
        if($where == "") {
            return [];
        } else {
            $where = substr($where, 4);
            return $this->createQueryBuilder('t')
                ->where($where)
                ->getQuery()
                ->getResult();
        }

    }
}
