<?php

namespace TerAelis\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeSujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSujetRepository extends EntityRepository
{
    public function findById($id) {
        return $this->findOneBy(array('id' => $id));
    }

    public function findByOrdre($ordre) {
        return $this->findOneBy(array('ordre' => $ordre));
    }

    public function getOrdreMax() {
        $lastType = $this->findOneBy(array(), array('ordre'=>'DESC'));
        if(!empty($lastType)) {
            return $lastType->getOrdre();
        } else {
            return 0;
        }
    }
}
