<?php

namespace TerAelis\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    public function getVote($user, $sondage) {
        return $this->createQueryBuilder('v')
            ->join('v.user', 'u')
            ->where('u.id = '.$user->getId())
            ->join('v.sondage', 's')
            ->andWhere('s.id = '.$sondage->getId())
            ->getQuery()
            ->getResult();
    }
}
