<?php

namespace TerAelis\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangRepository extends EntityRepository
{
}
