<?php

namespace TerAelis\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends EntityRepository
{
    public function findByUserGroup($user, $group) {
        $query = $this->createQueryBuilder('ur')
            ->join('ur.groupe', 'g')
            ->join('ur.user', 'u')
            ->where('g.id = '.$group->getId())
            ->andWhere('u.id = '.$user->getId())
            ->andWhere('ur.role = :role')
            ->getQuery()
            ->setMaxResults(1)
            ->setParameter('role', "usr")
            ->getResult();
        $res = null;
        foreach($query as $q) {
            $res = $q;
        }
        return $res;
    }
}
